### ISSUE TITLE
MESSAGES: Anzahl Empfänger bei Neu/Edit

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito_die_mitte#101]
Beim Erstellen/Editieren einer Nachricht soll angezeigt werden an wieviele Personen eine Nachricht gesendet wird.

- Für Briefe ist das bereits umgesetzt. Es gibt einen Link **Nachricht wird für 2 Personen erstellt.** welcher auf groups/1/mailing_lists/12/subscriptions.pdf zeigt. 
- Aktuell werden alle Personen mitgezählt, also auch solche ohne Adressen. 
- Es sollen nur noch Personen mit gültiger Nr (SMS) oder mit Adresse (Brief) mitgezählt werden. Siehe auch #105
- Beim Link auf subscriptions.pdf werden weiterhin alle Einträge mit und ohne Adresse oder Nummer angezeigt.
- Link-Text Brief anpassen: "Nachricht wird für 42 Personen erstellt. 3 weitere haben keine vollständige Adresse hinterlegt."
- Link-Text SMS: "Nachricht wird für 42 Personen erstellt. 3 weitere haben keine Mobiltelefonnummer hinterlegt."

# Techspec

https://github.com/hitobito/hitobito/blob/master/app/views/messages/_form.html.haml
Feature Test dafür schreiben

**Comment by olibrian** [comment]
Kann es sein, dass hier noch eine Übersetzung fehlt?
![image](https://user-images.githubusercontent.com/9592347/111660503-6d52e180-880e-11eb-8ec1-b2ff39a52fb5.png)

Url: https://die-mitte.puzzle.ch/de/groups/1/mailing_lists/9/messages/new?message%5Btype%5D=Message%3A%3ALetterWithInvoice
