### ISSUE TITLE
TECH: Umbenennen von cvp zu Die Mitte

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#104]
Die CVP hat ihren Name zu Die Mitte gewechselt. Dies führt zu einigen Anpassungen:

**Schreibweise**
Ausgeschrieben: Die Mitte
Kurze Form: die-mitte
Url: die-mitte.ch
Hitobito URL: db.die-mitte.ch
Farbcode: Blau: #003C69 Orange: #FF9B00

**Anpassen:**
- [x] fav icon #109 
- [x] Logo  #109 
- [x] github Repo hitobito_cvp neu hitobito_die_mitte 
- [x] github Repo  ose_composition_cvp ose_composition_die_mitte
- [x] Mailtrap
- [x] Jenkins
- [x] Highrise (obr)
- [x] Transifex Projekt 
- [x] Anpassen der Farben: #107 
- [x] Openshift Projekte (Int / Prod) und Overlays 

**Code Anpassungen**
- [x] neuen wagon (`die_mitte`) generieren
- [x] Code kopieren, `Cvp` modul durch `DieMitte` ersetzen
- [x] License Header anpassen

Gibt es noch weitere Abhängigkeiten?

- [x] DNS zur Integration, siehe https://gitlab.puzzle.ch/pitc_sys/pitc-dns/-/merge_requests/500
- [x] mail-adressen, siehe https://gitlab.puzzle.ch/pitc_ansible/ansible-puzzle/-/merge_requests/1931

**Comment by carlobeltrame** [comment]
Die bestehende Konvention von Pro Natura her wäre hitobito_die_mitte mit Underscores statt Bindestrichen. In URLs heissts natürlich trotzdem die-mitte.

**Comment by kronn** [comment]
Fehlende Punkte:
- [ ] DNS zur Integration
- [ ] mail-adressen

**Comment by kronn** [comment]
@psunix ich gebe das mal dir zum Review.

**Comment by psunix** [comment]
@kronn merci!

- die wagon tests failen noch (schaue ich gleich selber an)
- in config/settings.yml ist noch hitobito-cvp@puzzle.ch hinterlegt. bleibt das so?
- cryptopus team habe ich renamed, dort steht noch was von WIP prod account drin?
- auf appuio hat es momentan ein cvp und ein die-mitte projekt. ist da noch eine migration pending oder kann man das cvp projekt löschen?
- dito für integration, cvp.puzzle.ch ist immer noch aktiv
- im hitobito kustomize existieren noch die overlays für die cvp umgebungen, löschen?

von mir aus können wir gerne ein neues ticket machen für die noch offenen Punkte, meinst du das macht Sinn?

**Comment by kronn** [comment]
@psunix ich habe bereits ein follow-up ticket #117 angelegt und noch die Punkte von dir ergänzt, die gefehlt haben.
