### ISSUE TITLE
MESSAGES: Brief und Druckauftrag

### ISSUE THREAD

**Issue by psunix** [hitobito/hitobito_die_mitte#111]
Das Zusammenspiel von Brief und Druckauftrag muss noch finalisiert werden:

- Sobald für einen Brief ein Druckauftrag vorhanden ist, soll dieser nicht mehr bearbeitet werden können
-  wenn wir es so lösen würde ich aber einen Bestätigungs-Dialog oder eine Warnung auf dem Button oder so etwas ähnliches beim Erstellen des Auftrags anzeigen, damit der User weiss dass er vorher noch alle Typos korrigieren muss.

# Techspec

- https://github.com/hitobito/hitobito/blob/master/app/controllers/assignments_controller.rb
- Der Action Button (Druckauftrag erteilen) auf dem Brief führt auf DispatchController#new, was eine Flash-Message setzt und direkt auf den AssignmentsController#new weiterleitet
- Nach dieser Weiterleitung soll die Flash-Message angezeigt werden. Diese weist den User darauf hin, dass nach dem Erstellen des Druckauftrags der Brief nicht mehr abgeändert werden kann.
- Auf AssignmentsController#new soll der return_path zurück zum Brief führen
- Auf Assignment brauchts einen after_create Hook, der versucht auf dem Attachment Model eine Methode `prepare_print!` aufzurufen. Diese Methode erstellt via Dispatcher die definitive Recipients-Liste in der DB.
- [x] beim Senden einer SMS wird noch die Nachricht Druckauftrag erstellt angezeigt. Sollte wohl eher was mit SMS heissen
- [x] Message#show: Typ Feld entfernen, Typ als Prefix in Titel: SMS: 42 is the answer, Brief: Sommerlager
- [x] Message#show: status auch bei Entwurf anzeigen

**Comment by carlobeltrame** [comment]
@psunix wenn wir es so lösen würde ich aber einen Bestätigungs-Dialog oder eine Warnung auf dem Button oder so etwas ähnliches beim Erstellen des Auftrags anzeigen, damit der User weiss dass er vorher noch alle Typos korrigieren muss.
