### ISSUE TITLE
MESSAGES: Briefe können nicht generiert werden

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#112]
# Aktuelles Verhalten

Beim erstellen von einem Brief gibt es ein 500er

Getestet mit:
https://cvp.puzzle.ch/groups/1/mailing_lists/12/messages/8

TODO: Besser beschreiben wo das Problem ensteht? Click auf Button?

Konnte das Problem nicht nachkonstruieren. Was heisst Briefe generieren?

# Gewünschtes Verhalten

Briefe können generiert werden ohne Fehler.

# Techspec

- Gibt es ein Sentry Eintrag dafür?

**Comment by carlobeltrame** [comment]
Können wir nicht mehr reproduzieren. Bitte erneut eröffnen falls es wieder auftritt.
