### ISSUE TITLE
Cleanup renaming-remainders

### ISSUE THREAD

**Issue by kronn** [hitobito/hitobito_die_mitte#117]
Some things in #104 cannot be renamed, but need to be rebuilt with a new name, this leads to a needed cleanup.

## Technical Tasks
- [x] Zugriff über db.die-mitte.ch funktioniert noch nicht. Application is not available.  DNS ist eingetragen.
- [x] delete hit-cvp-int on https://openshift.puzzle.ch/
- [x] delete htbt-cvp-prod on https://console.appuio.ch
- [x] delete cvp.puzzle.ch in https://gitlab.puzzle.ch/pitc_sys/pitc-dns/-/edit/master/config/puzzle.ch/puzzle.ch.yaml
- [x] delete old overlays in kustomize
- login-adresse von hitobito-cvp@puzzle.ch auf hitobito-die-mitte@puzzle.ch ändern
  - [x] settings
  - [x] cryptopus
  - [x] int-db
  - [x] prod-db
  - [x] mailversand an hitobito-die-mitte@puzzle.ch sicherstellen

**Comment by kronn** [comment]
Die Umstellung der Mailadresse hitobito-cvp auf hitobito-die-mitte ist angedacht, sollte aber erst vollzogen werden, wenn die Mailadresse auch funktioniert. Die nötigen Systemumstellungen sind vorbereitet, aber noch nicht übernommen: https://gitlab.puzzle.ch/pitc_ansible/ansible-puzzle/-/merge_requests/2241

**Comment by kronn** [comment]
Die Systemanpassungen sind vorgenommen.

**Comment by psunix** [comment]
habe noch https://wiki.puzzle.ch/Hitobito/Umgebungen updated.
