### ISSUE TITLE
Rückmeldungen aus den Schulungen

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_die_mitte#121]
Kommentar von @ZuegerCVP 
> Hoi Andreas,
> Habe ein paar Rückfragen aus den Schulungen:
> - Die Suche über alle auf bestimmte Begriffe wie Familienmitglied: Seid ihr da dran dies noch auszudehnen auf alle und nicht nur die ersten paar? Weiter wäre es möglich, dass auch dort Optionen möglich sind, wie diese Personen zu Markieren und ihnen dann eine Rolle oder so zu geben. oder ein Export zu machen?
> - Wie genau ist die Suche eingestellt, sprich wenn ich bspw. die Rolle "Weitere Mandate" speziell bezeichne, kann ich dann direkt nach dieser Bezeichnung suchen oder muss diese Bezeichnung zuerst in die Suche aufgenommen werden? Diese Info brauche ich, dass ich den Nutzern erklären kann, wie sie suchen können und was nicht möglich ist. Zudem, es stimmt schon dass ich auch nach Fragmenten eines Begriffs suchen kann, also wenn ich "Fam" suche zeigt es mich auch die Familien an oder?

**Comment by olibrian** [comment]
Rolle kann via Filter gesucht werden.
Nach dem Bezeichnungsfeld kann aktuell nicht gesucht werden.
