### ISSUE TITLE
ROLLEN: Übersetzung von Rollen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#122]
Folgende Übersetzungsfehler sind noch aufgetaucht:

- [ ] Die Rollen sind im Transifex übersetzt aber werden in der Applikation nicht korrekt angezeigt.

![Screenshot from 2021-03-03 16-02-24](https://user-images.githubusercontent.com/9592347/109825261-f0364280-7c39-11eb-91f7-e2200c629734.png)

- [ ] Felder auf der Person sind nicht übersetzt und auch nicht in Transifex zu finden.

![image](https://user-images.githubusercontent.com/9592347/109836904-ed8d1a80-7c44-11eb-970a-a12392b26109.png)

- [ ] Auch die Gruppentypen werden nicht übersetzt:
![image](https://user-images.githubusercontent.com/9592347/111656312-b1dc7e00-880a-11eb-804e-c9451d2f26e2.png)

**Comment by TheWalkingLeek** [comment]
Fixed in https://github.com/hitobito/hitobito_die_mitte/commit/23db0df4f31fc1fa1946be4ba9b91d3c906ce960
