### ISSUE TITLE
MESSAGE: Auswahl ob PDF oder Rohdaten geliefert werden sollen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#127]
Abhängig vom gewünschten Produkt braucht die Druckerei ein fertiges PDF oder eine Excel (CSV) Liste mit den nötigen Attributen. Mit der Excelliste erstellt die Druckerei selbständig ein Serienbrief.

~Im Druckauftrag (https://die-mitte.puzzle.ch/de/assignments/new) soll es die Möglichkeit geben, auszuwählen ob ein PDF oder eine Excel Liste geschickt werden soll.~

Nach einem gestellten Auftrag kann entweder das PDF oder das CSV heruntergeladen werden. Dies erfolgt in der Ansicht des Briefes:
https://die-mitte.puzzle.ch/de/groups/1/mailing_lists/18/messages/40?returning=true

PDF: Wie bis anhin (bereits umgesetzt)
CSV-Export Liste: 
* Bei einem **Brief** wird die gleiche Liste wie im Abo mitgeschickt (https://die-mitte.puzzle.ch/de/groups/1/mailing_lists/9/subscriptions.xlsx?returning=true)
* Bei einem **Rechnungsbrief** braucht es noch weitere Informationen. Die Liste ist analog dem Export, wie wir in Vergangenheit manuell erstellt haben. Siehe #167

# Mockup

![image](https://user-images.githubusercontent.com/9592347/128510170-5f3fb365-6b24-4cae-a383-c24c1e760e69.png)

# Tech-Spec

- [ ] Script aus #167 in Export umwandeln, Zielformat ist CSV
- [ ] Headerzeile hinzufügen (ist im "in puncto" nicht vorhanden)
- [x] ~Auswahl, ob PDF oder CSV, erfolgt im Druckauftrag~
- [x] ~Default ist PDF~
- [ ] Möglichkeit bieten das CSV in der Ansicht des Briefes (https://die-mitte.puzzle.ch/de/groups/1/mailing_lists/18/messages/40?returning=true) herunterzuladen

**Comment by kronn** [comment]
@olibrian ich bin hier sehr unsicher, was noch fehlt. Wenn wir das weiterpushen wollen, hätte ich gerne einen Kontakt bei der Druckerei oder der Mitte, um die Integration zu testen. Ich denke, im Dialog wird da vieles klarer.

**Comment by olibrian** [comment]
Nach Rücksprache mit dem Kunde konnten wir dieses Ticket noch vereinfachen. Eine Auswahl ist nicht mehr nötig, sondern auf dem Brief soll entweder das PDF oder CSV heruntergeladen werden können. Beschreibung oben wurde angepasst.

**Comment by chrusu** [comment]
@TheWalkingLeek @luca-bruegger @kronn @carlobeltrame Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Development-601915cf57bc050017cf9a8c/issues/hitobito/hitobito_die_mitte/127?planning-poker)
