### ISSUE TITLE
MESSAGE: Rechnungsbrief in Abo ist nicht sichtbar

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#141]
## Aktuelles Verhalten

Auf dem Abo in der Prod gibt es keinen Button Rechnungsbrief:
![image](https://user-images.githubusercontent.com/9592347/112955073-57fb8280-913f-11eb-8ec6-607e9a1fbd8b.png)

Getestet mit Abo: https://db.die-mitte.ch/de/groups/1/mailing_lists/1/messages
User: Stefan Züger 

## Gewünschtes Verhalten

Wie auf der Integration soll auch ein Rechnungsbrief möglich sein

## Schritte zum reproduzieren

1. Auf einem Abo
2. Im Tab "Nachrichten"
3. Button fehlt

# Tech-Spec

- ...
- https://github.com/hitobito/hitobito/

**Comment by amaierhofer** [comment]
Der Button erscheint nur, wenn auf der Ebene die gültige Rechnungseinstellungen hinterlegt sind. Leider ist das UI diesbezüglich nicht konstistent

**Comment by olibrian** [comment]
Kunde hat Rechnungseinstellungen ergänzt, Button ist jetzt vorhanden
