### ISSUE TITLE
Email Adressen auf Familien nicht übernommen

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_die_mitte#143]
Im alten System wurden in Familien mehrmals die gleiche Email Adresse vergeben, so war es möglich einen Familie wie folgt abzubilden

- 1, Heinz und Herta Maier maier@example.com
- 2, Heinz Maier  maier@example.com
- 3, Herta Maier maier@example.com

Da in hitobito aber die Email Adresse als Login verwendet wird und folglich eindeutig sein muss, wurde die Email nur einmal übernommen. Manchmal auch nur auf dem Familienmitglied (Heinz und Herta) welches dann in Folge der Familienbereinigung gelöscht wurde.  Betroffen sind ca. tausend Personen, dh eine automatisierte Bereinigung ist hier wünschenswert.

Vorgehen
1. Kundennummern mit doppelt vergebenen Emails ermitteln, welche nicht übernommen wurden
2. Person mit Kundennummer (und ohne email) finden
3. Plausibelste Person ermitteln, wenn Kundennummer mehreren Personen zugeordnet ist (Familie)
4. Emails auf Person updaten.

**Comment by ZuegerCVP** [comment]
Weitere Beispiele aus dem Kanton Luzern sind:
Steiger-Müller Marcel 
Schlegel Martin
Peter-Vogel Ignaz 
Bucheli-Brunner Hanspeter
Emmenegger-Singer Monika

Diese sind jetzt korrigiert da ein Export gemacht werden musste.

**Comment by amaierhofer** [comment]
Fehlenden Emails wurden auf prod ergänzt
