### ISSUE TITLE
MESSAGE: Timeout bei Rechnungsvorschau

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#146]
## Aktuelles Verhalten

Meldung von Stefan:

Wir erhalten eine Fehlermeldung, wenn ein Brief oder Rechnungsbrief erstellt werden wollte, wir haben die Abonennten rausgenommen dann hat zumindest das funktioniert. https://db.die-mitte.ch/de/groups/169/mailing_lists/79/messages/65

504 Gateway Time-out. The server didn’t respond in time. das wäre die Meldung die er und auch ich erhalten...

## Gewünschtes Verhalten

Auch grössere Versände können ohne Time-out angeschaut werden.

## Schritte zum reproduzieren

1. Vorschau im erwähnten Abo auswählen
2. Server meldet Time-out

# Tech-Spec

* Bei der Vorschau nur einen Empfänger nehmen
* Beim definitiven Dokument in asynchronen Download auslagern --> siehe Abo-Mitglieder-Export

Branch: https://github.com/hitobito/hitobito/compare/bug/die-mitte-146_invoice_timeout

**Comment by amaierhofer** [comment]
Ich habe die Vermutung, dass das Generieren des PDFs schon recht lang geht. Ich glaube wir laufen da bei grösseren Empfänger Gruppen (> 50) schon in Timeouts. Wahrscheinlich tragen logo und wysiwyg content dazu massgeblich bei. 

Beim Rechnungsbriefen wird zudem bei der Vorschau auch noch die konkrete Rechnung validiert, und mitunter ein spezifische QR Code erstellt. Ich denke die Datenbank abfragen (obwohl redundant) sind für die aktuellen Timeouts nicht massgeblich.

**Comment by carlobeltrame** [comment]
@amaierhofer das sollte aber mit unseren Massnahmen trotzdem gelöst sein oder? Bei der Vorschau nur ein Empfänger, und beim echten PDF ein Async Download mit Job der das PDF im Hintergrund erstellt.

**Comment by psunix** [comment]
@amaierhofer meinte gestern das das generieren des PDF für die 4800 Empfänger 20min gedauert hat. das ist auch für einen Job definitiv zu viel!

**Comment by amaierhofer** [comment]
Preview mit einem einzelnen oder wenigen Empfänger finde ich sinnvoll. 

Async Download gefällt mir nicht so, besser fände ich wenn das PDF ím job erstellt und erst anschliessend zum Download verfügbar gemacht wird. 

Wir müssen auch berücksichtigen, das 4000 nicht die Obergrenzen für eine Versand sein wird. Es kann gut auch Versände an 10.000 oder 100.000 Empfänger geben.

**Comment by carlobeltrame** [comment]
I see. Das heisst also die Grundsatzentscheidung die wir ganz am Anfang vom Entwickeln der Messages getroffen haben, dass die PDFs immer on the fly gerendert werden, stellt sich jetzt als falsch heraus. Das umzustellen bedeutet auch, Speicherplatzproblemen entgegenzuwirken. Ich glaube beim Konzept des Auftragsmoduls haben wir uns auch darauf abgestützt dass das PDF on the fly gemacht wird. Und der Job der 20 Minuten läuft lässt sich so oder so nicht vermeiden, wenn das Generieren so lange dauert.

Ich würde den PR #1255 trotzdem mal mergen, da er bei mittelgrossen Briefen bereits eine Verbesserung gegenüber dem aktuellen Stand darstellt, und dann in einem separaten Ticket noch alle Auswirkungen der grossen Umentscheidung abschätzen. Auf jeden Fall sprengt das die 3 Punkte dieser Story bei weitem.
