### ISSUE TITLE
MESSAGE: Rechnung ohne Betrag

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#148]
Aktuell werden sind nur Rechnungen mit einem Betrag möglich. Wenn kein Wert eingetragen wird, führt dies zu einem Fehler. Siehe https://github.com/hitobito/hitobito/issues/1236 

Ziel ist eine Rechnung, ohne definierten Betrag, erstellen zu können. Betrag soll dabei leer sein und nicht 0. Somit kann der Rechnungsempfänger wahlweise einen Betrag einfüllen.

- [ ] Anpassungen am QR Code 
- [ ] Verhindern, dass Rechnungen mit leeren Rechnungsartikel angelegt werden (hitobito/hitobito#1236)

Gemäss: https://www.paymentstandards.ch/dam/downloads/style-guide-de.pdf (Beispiel Seite 23)
Ist im Swiss QR Code kein Betrag enthalten, muss ein farbloses Feld mit den Massen 30 x 10 mm und schwarzen Eckmarken mit einer Linien-stärke von 0,75 pt aufgedruckt sein, in dem der Betrag vom Zahlungspflichtigen handschriftlich zu ergänzen ist.

- [ ] Anpassungen an den Rechnungsartikel
- [ ] Rechnungen auf einer Person erstellen
- [ ] Rechnungen auf einem Abo erstellen
- [ ] Rechnungsbrief auf Abo erstellen

# Mockup

# Tech-Spec

**Comment by amaierhofer** [comment]
Minimale Umsetzung, nur für RechnungsBrief / Sammelrechnungen, siehe https://github.com/hitobito/hitobito/tree/feature/148-mitte-invoice-without-amount

- Keine Anpassungen am UI (Betrag wird weiterhin mit 0.0 angezeigt)
- In dem QR Zahlteil wird der Betrag nicht mehr angezeigt (qr code validiert)
- Rechnung kann gestellt werden
- Zahlungen können erfasst werden

Weiteres Vorgehen TBD
- Sollen Anpassungen am UI gemacht werden?
- Auch normale Rechnung ohne Rechnungsartikel stellen?
- andere Einzahlungsscheine ?

- Keine Anpassungen am UI (Betrag wird weiterhin mit 0.0 angezeigt)
- In dem QR Zahlteil wird der Betrag nicht mehr angezeigt (qr code validiert)
- Rechnung kann gestellt werden
- Zahlungen können erfasst werden

Weiteres Vorgehen TBD
- Sollen Anpassungen am UI gemacht werden?
- Auch normale Rechnung ohne Rechnungsartikel stellen?
- andere Einzahlungsscheine ?
