### ISSUE TITLE
MESSAGE: Performance bei Erstellen von Briefen/Rechnungen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#153]
## Aktuelles Verhalten

Die Generierung von PDFs dauert sehr lange (ca 20 Minuten bei 4800 Empfängern). Diese Anzahl ist keine Seltenheit, es ist eher damit zu rechnen, dass noch grössere PDFs generiert werden. Versände bis ca 10k Personen können wohl schon vorkommen.

Als Massnahme wurde ein asynchroner Download implementiert. 

## Gewünschtes Verhalten

Kann die Generierung noch optimiert werden? Siehe Diskussion https://github.com/hitobito/hitobito_die_mitte/issues/146#issuecomment-823937073

## Schritte zum reproduzieren

1. Umfangreiche Briefe (z.b. 100 Empfänger: https://die-mitte.puzzle.ch/de/groups/303/mailing_lists/23/messages/47)

# Tech-Spec

- ...

**Comment by amaierhofer** [comment]
Das Generieren des PDFs eine Beispiel Rechnungsbrief (Logo, Einzahlungschein, 2000 Zeichen Text) ist sehr langsam und wird mit zunehmender Empfänger Anzahl leider noch langsamer (skaliert schlechter als linear). Die Zeit geht im wesentlichen für das Rendern des PDFs drauf. Unsere PDF Bibliothek bietet die Möglichkeit statischen Inhalt wiederzuverwenden (stamping).
Dadurch wird die Performance massgeblich verbessert. 

| Empfänger | normal | stamped |
| --- | --- |---|
| 10 | 1.2 | 0.7 |
| 100 | 3.8 | 1 |
| 1000 | 45 | 11 |
| 2000 | 128 | 28 |
| 4000 | 400 | 44 |
| 8000 | 1296 | 90 |
| 16000 | 5593 | 148 |
| 32000 | - | 319 |


Allerdings ist der Performance Gewinn nur dann tatsächlich realisierbar, wenn der Inhalt identisch ist. Daher wird empfohlen für grosse Versände keine Platzhalter im Text zuverwenden und statt dessen die Anrede in ein eigenes  Feld auszulagern #158
