### ISSUE TITLE
MIGRATION: Übernahme des Attributes Zivilstand

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#156]
Bei der Migration wurde das Attribut Zivilstand auf der Person noch nicht übernommen.
Definiertes Attriubt auf der Person heisst `person_civil_status`

# Tech-Spec

- https://github.com/hitobito/hitobito

**Comment by amaierhofer** [comment]
@olibrian Bist du sicher, dass um Zivilstand geht. Soweit ich das sehe wurde das Attribute bereits bei der Migration befüllt

**Comment by amaierhofer** [comment]
Gab bereits Änderungen auf prod und der default `single` hat mich verwirrt. Ich habe jetzt die Zivilstände `geschieden`, `verheiratet`, `verwitwet` und `Konkobinat` aus den alten Daten übernommen.
