### ISSUE TITLE
Abos: Inkonsistente Abo Berechtigungen

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_die_mitte#161]
## Aktuelles Verhalten

Als Sekretär auf Ebene Bund werden mit die Abos eines Kantons anzeigt, allerdings fehlen die Berechtigungen zum Ansehen des Abos 

## Gewünschtes Verhalten

Sekretär kann das Abos anzeigen oder die Liste ist leer

## Schritte zum reproduzieren

1. Ohne Rolle Sekretär im Kanton die Abo Kiste aufrufen
2. Beliebiges Abo der Liste öffnen

# Tech-Spec

Unklar ob das ein CVP spezifisches Problem ist oder nicht. Dringlichkeit nicht sehr hoch, da eine sprechende Fehlermeldung angezeigt wird.

**Comment by olibrian** [comment]
Wurde mit "Personen mit layer_and_below_full Berechtigung dürfen Personenfilter auf tieferen Layern bearbeiten, erstellen & löschen" gelöst. See: https://github.com/hitobito/hitobito/commit/4e53b62d263591fdec1a8c01242a232af143780a
