### ISSUE TITLE
MESSAGE: Bild im Text anzeigen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#163]
## Aktuelles Verhalten

Die Unterschriften (Bild) in Briefen können reingeladen werden und werden im Editor auch angezeigt. Beim generieren der Vorschau oder des fertigen PDFs sind die Unterschriften aber nicht sichtbar.

## Gewünschtes Verhalten

Anzeigen von Bild im PDF wie im Editor

## Schritte zum reproduzieren

1. Brief erstellen
2. Im Edior ein Bild einfügen (Attach file)
3. PDF generieren

Beispiel: https://die-mitte.puzzle.ch/de/groups/1/mailing_lists/18/messages/32

# Tech-Spec

Ursprüngliches Ticket: https://github.com/hitobito/hitobito_die_mitte/issues/92 
Ev ein Zusammenhang mit Zugriff auf User-Content in Openshift (just guessing)

**Comment by amaierhofer** [comment]
Wahrscheinlich ein Problem im production environment, im development environment funktioniert die Darstellung im PDF und HTML
![Screenshot from 2021-05-06 09-10-13](https://user-images.githubusercontent.com/180780/117256597-2c10a280-ae4b-11eb-9dbb-47ef0663df29.png)

**Comment by amaierhofer** [comment]
Sehr mysteriöses Problem, kann noch immer nicht erklären, was genau abläuft,
- wenn ich`eager_load = true` setze in produkten werden die bilder angezeigt.
- ebenso bin ich in der lage bilder in unserem view code direkt anzuzeigen
