### ISSUE TITLE
EXPORT: Einmaliger Export für in puncto Versand

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#167]
Für den Versand des Magazins "in puncto" braucht die Mitte einen einmaligen Export für die Druckerei. Die Mitte erfasst ein Abo und erstellt eine Rechnung. Daten von dieser Sammelrechnungen sollen exportiert werden.

Ein Export, kombiniert aus den Tabellen Personen und Rechnungen mit folgenden Attribute

Rechnung

- Nummer
- Empfänger E-Mail
- Empfänger Adresse
- Referenz Nummer
- Betrag

Person

- Vorname
- Nachname
- Firmenname
- Firma
- Haupt-E-Mail
- Adresse
- PLZ
- Ort
- Land
- Geschlecht
- Geburtstag
- Anrede (Ausfüllt z.b. Sehr geehrte Frau Meier)
- Titel
- Korrespondenzsprache
- Wohnt im Haushalt mit (Checkbox)

Von der Person im Haushalt:
- Vorname
- Name
- Anrede
- Geschlecht
- Sprache
- Referenz Nummer der Rechnung

Ergänzung:
* Bei Haushalten nur eine Zeile exportieren (analog zur Haushaltsliste)

# Mockup

hier folgt ein Mockup ...

# Tech-Spec

- https://github.com/hitobito/hitobito

**Comment by carlobeltrame** [comment]
Zur späteren Referenz, hier das Skript das ich für diesen Export verwendet habe:
```ruby
m = Message::LetterWithInvoice.find(...)

def group_households(list)
  list.each_with_object(Hash.new { |h, k| h[k] = [] }) do |person, memo|
    memo[person.household_key.presence || SecureRandom.uuid] << person
  end.values
end

def household_cols(household)
  household.drop(1).map {|p| [p.first_name, p.last_name, Salutation.new(p).value, p.gender, p.correspondence_language]}.flatten
end

File.open("in-puncto.csv", "w") {|f| f.write(group_households(m.mailing_list.people.with_address.unscope(:select)).map {|people| p=people.first; i=m.invoice_for(p); [i.esr_number, i.recipient_email, i.recipient_address, i.reference, 0, p.first_name, p.last_name, p.company_name, p.company, p.email, p.address, p.zip_code, p.town, p.country, p.gender, p.birthday, Salutation.new(p).value, p.title, p.correspondence_language, p.household_key?].concat(household_cols(people)) }.inject([]) { |csv, row|  csv << CSV.generate_line(row) }.join(""))}
```

**Comment by carlobeltrame** [comment]
Der Export wurde inzwischen in https://github.com/hitobito/hitobito_die_mitte/commit/bc63b0eed46b30f0d2faf6a57cbe039c43c5e52d implementiert.
