### ISSUE TITLE
RECHNUNG: Berechnung "variabler Spendenaufruf"

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#173]
Bisherspendenaufruf auf Grundlage von vergangenen Spenden. Aufgrund der vergangenen Spenden soll ein idealer Betrag für den nächsten Spendenaufruf berechnet werden.

Grundlegende Formel: Letzte X Jahre, Y % erhöhen
    • Wenn X höher als 1, nur höchster Betrag
    • Runden:
        ◦ Bisherbetrag unter 100.- = runden auf 5 Franken
        ◦ Bisherbetrag unter 1000.- = runden auf 10 Franken
        ◦ Bisherbetrag über 1000.-= runden auf 50 Franken

Der Bisherbetrag beinhaltet alle Zahlungen auf einer Person, welche auf dem Layer erstellt wurden. Beispiel bei der Berechnung des Bisherbetrages auf dem Layer "Schweiz" werden sämtliche Bisherbeträge von dem Layer "Schweiz" beachtet. Rechnungen von anderen Layern werden für die Berechnung nicht berücksichtigt.

**Umsetzung:**
Einstellung pro Layer auf den Rechnungseinstellungen
Auslieferung der Daten: Die Daten werden als Excel ausgeliefert und nicht in eine Briefvorlage. (Details siehe https://github.com/hitobito/hitobito_die_mitte/issues/127 )

Siehe auch #181 für die weitere Integration.

# Mockup

Konfiguration des Spendenaufrufs erfolgt in den Rechnungsartikel pro Layer in einem zusätzlichen Abschnitt mit der Eingabe von den beiden Parametern: (Mockup ist als illustrativ zu verstehen nicht als Vorgabe)
![Screenshot from 2021-07-01 13-45-58](https://user-images.githubusercontent.com/9592347/124119386-be5fac00-da72-11eb-8ccc-6b4e297a4461.png)

# Tech-Spec

- [x] Domain-Klasse `Donations` für diese und andere Spendenaufrufsberechnungen anlegen.
- [x] `Donations.new.since(x_years.years.ago).of_person(person).previous_amount(increased_by: y_percent)`
- [x] "fluid interface" um nach und nach scope aufzubauen. -> Wiederverwendung in #174 
- [x] Setting auf Layergruppe (InvoiceConfig), wieviele Jahre betrachten werden sollen 
- [x] Setting auf Layergruppe (InvoiceConfig), wieviel Prozent erhöht werden sollen
- [x] vorerst alle Payments des Layers betrachten, da alle dort erfassten Zahlungen als "Spenden" zählen

**Comment by carlobeltrame** [comment]
### Besprechung mit Stefan

* Feature ist nur für Bund und Kantone nötig
* Sämtliche vergangenen Zahlungen werden als Spenden angesehen
* Variabler Spendenaufruf passiert höchstens einmal jährlich, berücksichtigt werden nur Zeitspannen in ganzen Jahren
* "Jahr" heisst 1. Januar bis 31. Dezember
* Rundungsregeln wie oben beschrieben können hartcodiert werden
