### ISSUE TITLE
RECHNUNG: Spendenbestätigung

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#174]
Personen, welche im vergangenen Kalenderjahr eine Spende getätigt haben, sollen eine Bestätigung erhalten.

Lösung: Wie im variablen Spendenaufruf (#173) werden die Zahlungen des letzten Jahres (01.01-31.12) zusammengerechnet. 
Die Spendenbestätigung wird auf einer Schriftgutvorlage "Spendenbestätigung" erstellt. 
Dieser Spendenbestätigung wird gleichzeitig eine leere QR-Code-Rechnung beigelegt. 
Diese Daten werden als PDF generiert und der Druckerei verschickt. Siehe dazu hitobito/hitobito_die_mitte#127

Für die Spendenbestätigung sind die Rechnungen vom aktuellen Layer relevant.

Der inhaltliche Text für die Spendenbestätigung ist bis auf die Jahreszahl fix.

Umsetzung:
    • Wie ein Rechnungsbrief ~~jedoch mit einem definierten Text mit der Spendenbestätigung~~
    • ~~Im Menü «Rechnungseinstellung»~~

# Tech-Spec

- [x] Die Spendenbestätigung ist ein normaler Rechnungsbrief, auf dem ein neues Flag "Spendenbestätigung" aktiviert ist
- [x] Wenn das Flag aktiviert ist, kommt unter dem Brieftext eine Zeile dazu, die den totalen Spendenbetrag vom Vorjahr enthält
- [x] Zahlungen des letzten Jahres zusammenrechnen (in Domain-Klasse `Donations` o. ä.)
- [ ] `Donations.in_last(1.year).in_layer(layer).confirmations # => [{person, donated_amount}]`
- [x] "fluid interface" um nach und nach scope aufzubauen. → Wiederverwendung von #173 
- [ ] ~~CustomContent für Text "Spendenbestätigung" ohne Platzhalter anlegen~~
- [x] Spendenbetrag steht separat, um den veränderlichen Textblock klein zu halten (stamping/Performance)
- [x] Das Jahr im Brief ist von den Kunden frei definierbar, da im Brieftext
- [x] leere Rechnung mit Referenznummer anhängen
- [x] in hitobito wird es als Invoice erstellt, um Zahlungen zuordnen zu können.

**Comment by chrusu** [comment]
@TheWalkingLeek @luca-bruegger @kronn @carlobeltrame Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/Development-601915cf57bc050017cf9a8c/issues/hitobito/hitobito_die_mitte/174?planning-poker)
