### ISSUE TITLE
API: Ergänzen von möglichen Rollen auf der Gruppe

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#176]
Für die Webseite soll auf der Gruppe die möglichen Rollen abgefragt werden. Abhängig vom Gruppentyp sollen die Rollen ausgegeben werden.

**Beispiel:**
Gruppentyp: Gewählte
Rollen:
* Bundesrat
* Bundeskanzler
* Ständerat
* Nationalrat
* Bundesrichter (Vollamt)
* Bundesrichter (Nebenamt)
* Bundesverwaltungsrichter
* Bundespatentrichter
* Bundesstrafrichter

Ziel ist dabei ein Filter auf der Webseite zu bauen, welche es erlaubt nach den möglichen Rollen zu filtern.

**Zusätzlich**: Zusätzlich sollten wir auch noch gleich auf der Person das `website` Feld in der API mitliefern (gibts nur im Die Mitte Wagon)

# Mockup

hier folgt ein Mockup ...

# Tech-Spec

- https://github.com/hitobito/hitobito

**Comment by carlobeltrame** [comment]
Mehrsprachiges Feld «Bezeichnung»

Die folgenden Gruppen, inkl. aller Untergruppen in diesen Gruppen sollen ins französische migriert werden. Bei allen andern Gruppen (und auch hier wieder in alle Untergruppen, soll das was bereits im Feld Bezeichung drin steht ins Deutsche Feld migriert werden. 

* Le Centre FR/ Die Mitte FR: https://db.die-mitte.ch/de/groups/158 
* Le Centre NE: https://db.die-mitte.ch/de/groups/164 
* Le Centre VD: https://db.die-mitte.ch/de/groups/174 
* PDC BE Jura sud: https://db.die-mitte.ch/de/groups/155 
* PDC GE: https://db.die-mitte.ch/de/groups/159 
* PDC JU: https://db.die-mitte.ch/de/groups/162 
* PDC VS. Romand: https://db.die-mitte.ch/de/groups/176 
* PPD TI: https://db.die-mitte.ch/de/groups/172 

Vereinigungen: 
Hier bitte aufpassen, da innerhalb der Vereinigung einige Gruppen französisch sein sollen, andere deutsch. Die französischen sind die folgenden (auch hier jeweils mit den Untergruppen). 
* Femmes TI: https://db.die-mitte.ch/de/groups/108 
* Femmes FR: https://db.die-mitte.ch/de/groups/37563 
* Femmes JU: https://db.die-mitte.ch/de/groups/98 
* Femmes NE: https://db.die-mitte.ch/de/groups/100 
* Femmes VD: https://db.die-mitte.ch/de/groups/110

* JDC FR/JCVP FR: https://db.die-mitte.ch/de/groups/241
* JCVP GE: https://db.die-mitte.ch/de/groups/38742
* JCVP JU: https://db.die-mitte.ch/de/groups/38800
* JCVP NE: https://db.die-mitte.ch/de/groups/36851
* JCVP TI: https://db.die-mitte.ch/de/groups/255
* JCVP Valais romand: https://db.die-mitte.ch/de/groups/52966
* Jeunes du Centre VD: https://db.die-mitte.ch/de/groups/257
