### ISSUE TITLE
ROLES: Bezeichnung mehrsprachig

### ISSUE THREAD

**Issue by carlobeltrame** [hitobito/hitobito_die_mitte#178]
Auf der Webseite möchte die Mitte nicht die genderunabhängigen Rollenbezeichnungen ("PräsidentIn" etc.) sondern spezifisch zu der jeweiligen Person passende Rollenbezeichnungen anzeigen. Dafür verwenden sie das "Bezeichnung" Feld auf der Rolle. Da die Webseite mehrsprachig ist, soll dieses Feld für die Mitte mehrsprachig gemacht werden.

Die bisher erfassten Bezeichnungen sollen je nach Gruppe als unterschiedliche Sprache übernommen werden. Stefan liefert noch eine Liste mit Zuordnungen von Gruppen zu Sprachen.

# Mockup

UI sieht wie bisher aus, aber wenn man auf eine andere Sprache umschaltet sollte man die Möglichkeit haben, die Bezeichnung auf diese Sprache zu erfassen.

# Tech-Spec

- Mit `globalize` / `translates` im Wagon das `label` Feld von Rollen übersetzbar machen
- Fallback-Verhalten falls die Bezeichnung auf eine Sprache nicht ausgefüllt ist
- Datenmigration schreiben
- Auswirkungen an diversen Stellen im UI testen:
  - Personenliste
  - Person Detailansicht
  - Export der Personenliste
  - ...

**Comment by kronn** [comment]
Mehrsprachiges Feld «Bezeichnung»

Die folgenden Gruppen, inkl. aller Untergruppen in diesen Gruppen sollen ins französische migriert werden. Bei allen andern Gruppen (und auch hier wieder in alle Untergruppen, soll das was bereits im Feld Bezeichung drin steht ins Deutsche Feld migriert werden.

    Le Centre FR/ Die Mitte FR: https://db.die-mitte.ch/de/groups/158
    Le Centre NE: https://db.die-mitte.ch/de/groups/164
    Le Centre VD: https://db.die-mitte.ch/de/groups/174
    PDC BE Jura sud: https://db.die-mitte.ch/de/groups/155
    PDC GE: https://db.die-mitte.ch/de/groups/159
    PDC JU: https://db.die-mitte.ch/de/groups/162
    PDC VS. Romand: https://db.die-mitte.ch/de/groups/176
    PPD TI: https://db.die-mitte.ch/de/groups/172

Vereinigungen:
Hier bitte aufpassen, da innerhalb der Vereinigung einige Gruppen französisch sein sollen, andere deutsch. Die französischen sind die folgenden (auch hier jeweils mit den Untergruppen).

    Femmes TI: https://db.die-mitte.ch/de/groups/108
    Femmes FR: https://db.die-mitte.ch/de/groups/37563
    Femmes JU: https://db.die-mitte.ch/de/groups/98
    Femmes NE: https://db.die-mitte.ch/de/groups/100
    Femmes VD: https://db.die-mitte.ch/de/groups/110
    JDC FR/JCVP FR: https://db.die-mitte.ch/de/groups/241
    JCVP GE: https://db.die-mitte.ch/de/groups/38742
    JCVP JU: https://db.die-mitte.ch/de/groups/38800
    JCVP NE: https://db.die-mitte.ch/de/groups/36851
    JCVP TI: https://db.die-mitte.ch/de/groups/255
    JCVP Valais romand: https://db.die-mitte.ch/de/groups/52966
    Jeunes du Centre VD: https://db.die-mitte.ch/de/groups/257
