### ISSUE TITLE
MIGR: Zahlungen Person zuweisen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#186]
Bei der Mitte gibt es noch einige Zahlungen, welche nicht einer Person zugeorndet sind. Die Zahlungen sind bereits in Hitobito vorhanden. 

- Möglichst viele dieser Zahlungen einer Person in Hitobito zuweisen. Dabei können die Personen welche im OM als gelöscht markiert wurden ignoriert werden. Dies ist in der Spalte Y mit einem L markiert.

- Die anderen Zahlungen (461 st) würden wir aufgrund der Maildresse versuchen einer Person in Hitobito zuzuweisen. Zahlungen welche wir so nicht zuweisen können, weil keine Maildreasse hinterlegt ist, oder keine Person diese Mailadresse in Hitobito hat, werden wir die Person neu in Hitobito erstellen. Diese Person bekommt eine Rolle in einer Gruppen auf nationaler Ebene. Dies kann aber potentiell zu Dubletten im System führen, dessen sind wir uns bewusst. Die Mitte kann diese Personen via Dubliaktsfilter ggf. zusammenführen.

Details in Daten per Mail.

**Comment by carlobeltrame** [comment]
Es sind nur 288 der 461 (nicht als gelöscht markierten) Zahlungen tatsächlich bereits in Hitobito vorhanden.
Zu 123 der 280 Mailadressen habe ich eine bestehende Person gefunden. Die restlichen 461 - 123 = 338 Personen werden neu angelegt.

**Comment by carlobeltrame** [comment]
Import ist erledigt auf Produktion.
