### ISSUE TITLE
MESSAGE: Export von Spendenbestätigung

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#192]
Wenn `Spendenbestätigung` gesetzt ist soll im CSV Export eine zusätzliche Spalte mit dem Betrag der Spendenbestätigung exportiert werden.

Beispiel eines Spendebestätigungsbriefes: https://die-mitte.puzzle.ch/de/groups/1/mailing_lists/43/messages/145

https://die-mitte.puzzle.ch/de/groups/1/mailing_lists/9/messages/149

# Mockup

hier folgt ein Mockup ...

# Tech-Spec

- Umsetzung im Wagon https://github.com/hitobito/hitobito_die_mitte weil der CSV-Export auch im Wagon ist
- Berechnung gleich wie fürs PDF: https://github.com/hitobito/hitobito/blob/master/app/domain/export/pdf/messages/letter_with_invoice/donation_confirmation.rb#L81
- Entsprechende Methode in https://github.com/hitobito/hitobito_die_mitte/blob/master/app/domain/export/tabular/messages/letter_row.rb und https://github.com/hitobito/hitobito_die_mitte/blob/master/app/domain/export/tabular/messages/letters_with_invoice_row.rb ergänzen
- Attribut in https://github.com/hitobito/hitobito_die_mitte/blob/master/app/domain/export/tabular/messages/letters.rb und https://github.com/hitobito/hitobito_die_mitte/blob/master/app/domain/export/tabular/messages/letters_with_invoice.rb ergänzen
- Specs anpassen und erweitern

**Comment by TheWalkingLeek** [comment]
Auch auf dem normalen Letter? Aktuell kann man nur LetterWithInvoice als Spendenbestätigung flaggen: https://github.com/hitobito/hitobito/blob/master/app/views/messages/letter/_fields.html.haml#L17

**Comment by carlobeltrame** [comment]
Oh, das war mir nicht bewusst. Dann machts wohl nur bei Rechnungsbriefen Sinn.
