### ISSUE TITLE
MESSAGES: Dynamische Elemente Logo und Absender im PDF Brief/Rechnung

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#24]
**Ist**
Aktuell werden auf dem Brief ein hitobito Logo angezeigt und ein Standard Absender angezeigt.

**Soll**
Folgende Einstellungen/Informationen werden für den PDF Brief und Rechnung aus hitobito dynamisch aufgenommen:

**Absender:** 

Kontaktangaben der jeweiligen Gruppe, wo der Brief generiert wurde. 
Fallbackverhalten: Kontaktangaben vom Layer verwenden.

~~Falls weder auf der Gruppe noch auf dem Layer eine Kontaktangabe vorhanden ist, kann dies bei der Brieferstellung nicht ausgewählt werden (Checkbox)~~
Falls keine Adresse auf Gruppe und Layer vorhanden ist, wird einfach eine leere Box/Platzhalter gedruckt. 

**Logo:** 
Das Logo aus den jeweiligen Gruppeneinstellungen verwenden. Möglichkeit eigenes Logo unter Einstellungen pro Gruppe (https://cvp.puzzle.ch/groups/3/settings) hochladen. Fallbackverhalten: Logo vom Layer verwenden.
~~Falls auf der Gruppe kein Logo vorhaneden ist, kann dies bei der Brieferstellung nicht ausgewählt werden (Checkbox)~~
Falls kein Logo auf Gruppe und Layer vorhanden ist, wird einfach eine leere Box gedruckt.

# Mockup 

![image](https://user-images.githubusercontent.com/9592347/107616505-7fa99080-6c4e-11eb-8b69-da878df08550.png)

# Techspec
- [x] Dateiupload für Brieflogo in den Gruppeneinstellungen, Carrier-Wave erstellen.
- [x] PDF-Generierung: Logo und Kontaktangabe einbinden
- [x] Brief erstellen / Rechnungsbrief erstellen: Logo und Kontaktangabe einbinden
- [x] Brieferstellen: Checkbox Briefkopf für Logo und Kontaktangaben

**Comment by olibrian** [comment]
Welche Vorlagen notwendig sind, ist bei Stefan in Abklärung.

**Comment by amaierhofer** [comment]
Weitere Fragen dazu
- Wie viele verschiedene Logos wird es geben?
- Soll pro Brief ein Logo ausgewählt werden oder verwendet eine Gruppe (Layer) immer das gleiche Logo?
- Wie häufig werden diese Logos ändern?

**Comment by olibrian** [comment]
Möglichkeiten für generische Umsetzung:
Absender: Kontaktangaben der jeweiligen Gruppe, wo der Brief generiert wurde.
Logo: Logo von der jeweiligen Gruppe verwenden, Fallback wie in der Applikation
