### ISSUE TITLE
Abbilden von Familienadressen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#53]
Ziel: Personen sollen zu Familien zusammengeschlossen werden können. Diese sind wiederum für Rechnungen (Betrag und anz. Rechnungen) und Korrespondenz (physische Versände). Aktuell gibt es rund 8000 Familienmitgliedschaften. Familienmitglieder haben im aktuellen System die gleiche `Kundennummer` und ein sequenziell ansteigende `Kontaktnummer`. Dieses Konzept `Kundennummer` und `Kontaktnummer` wird auch verwendet um Angehörige von Firmen zu gruppieren. Auf der `Mitgliedschaft` ist vermerkt ob es sich um einen Familienmitgliedschaft handelt.

Lösungsmöglichkeiten:
- Eigene Rolle `Familienmitglied`, die den Mitgliedern einer Familie vergeben wird.
- Bestehende Attribute übernehmen, und nur beim Versenden von Rechnungen berücksichtigen

Ein zusätzliches Konzept ist "Haushalt", womit Personen mit der gleiche Adresse zusammengefasst werden. Damit haben diese Personen *zwingend die gleiche Addresse*

**Comment by amaierhofer** [comment]
Vorschlag: 

Neue Spalten (mit Übersetzungen und aufnahmen in controller `attrs_accessible`)
- groups families, boolean, default false (Familienmitglieder) (anzeigen und editierbar, nur auf kantonaler Ebene)
- people familiy, boolean, default false (Familienmitglied) (nur anzeigen)

Beim Speichern der Person, falls die Person eine Rolle `Role::Mitglied` in einem Verband hat, der Familienmitgliedschaften unterstützt. Als Domain Object `People::FamiliyMember` implementieren und als `after_save` im PeopleController aufrufen
- Wenn der `household_key` gesetzt ist, bei einen Personen `family` auf true setzen
- Wenn der `household_key` nicht gesetzt ist, `family` auf false setzen

**Comment by olibrian** [comment]
Wird über "Haushalt" abgebildet.
