### ISSUE TITLE
Weitere Anpassungen an den Rollen

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_die_mitte#89]
Gemäss Nachricht von Stefan

- Ebene Vereinigungen (nur für die nationale Ebene der Vereinigung): Gruppe Delegierte (Rollen: Delegierte / Ersatzdelegierte)
- In Ebene Bund, Gruppe Gewählte Rolle: Bundeskanzler
- In Ebene Kanton, Gruppe Gewählte: Weitere Mandate

Entsprechend Rollen anlegen und Merkmale bei für die Migration konfigurieren

**Comment by ZuegerCVP** [comment]
Eine weitere Rolle habe ich noch: 
Auf Ebene Kanton, Region, Ort und Vereinigung jeweils in der Gruppe Sekretariat: **Webadministrator** (noch ohne Berechtigungen)

**Comment by ZuegerCVP** [comment]
Bin gerade die Organisation Hierarchy duchgegangen und habe einige Rollen und Gruppen gefunden, wo ich nicht genau weiss woher sie kommen. Haben wir, so weit ich weiss ursprünglich nicht drin gehabt. 
Ebene Kanton: Gruppe Spender; löschen
Ebene Region: Gruppe Gewählte; löschen
Ebene Ort: Gruppe Spender; löschen

**Comment by ZuegerCVP** [comment]
Die Finale Liste der Merkmale mit Zuordnung Gruppen und Rollen habe ich an @amaierhofer geschickt da ich hier kein CSV hochladen kann. 

Eine Rolle kommt dazu:
Auf Ebene Bund und Kanton: Gruppe Delegierte die Rolle: "Delegierte von Amtes wegen"
Danke für die Arbeit!

**Comment by amaierhofer** [comment]
- [x] Webadministrator im Sekretariat auf allen Ebenen
- [x] Gruppe `Kanton::Spender` löschen
- [x ] Gruppe `Ort::Spender` löschen
- [ ] `Region::Gewaehlte` löschen - aktuelle legen wir solche Gruppen an, einige gibt es in bl (zb. https://github.com/hitobito/hitobito_cvp/blob/ea45f12bfb054081e769a838e0692d5b04f6443d/generated/roles/bl.txt#L41) aber auch noch in diversen anderen Kantonen, sollen das alles Orte werden? Will du da nochmal drüber schauen @ZuegerCVP
