### ISSUE TITLE
Bild im Editor

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_die_mitte#92]
Im Editor die Möglichkeit bieten ein Bild (z.b. Unterschrift) einzufügen.

**Comment by carlobeltrame** [comment]
ActionText unterstützt das bereits von Haus aus, aber ich habe es für CustomContents und HelpTexts absichtlich deaktiviert.
Das zu deaktivieren ist leider von ActionText nicht von Haus aus "unterstützt", daher musste ich drei Schritte unternehmen:
- Ich habe einen Validator geschrieben, der kontrolliert dass ein ActionText Feld keine Attachments hat. Den Validator kann man je nach Bedarf auf das Model-Feld machen (`no_attachments: true`) oder auch nicht.
- In actiontext.scss zuunterst habe ich die attachment Buttons auf der ActionText Toolbar mit CSS ausgeblendet. Hier müsste man eine Lösung finden wie man das pro Feld ein- und ausblenden kann.
- In application.js zuunterst habe ich via JS drag-and-drop file attachments deaktiviert. Auch hier müsste eine Lösung gefunden werden die das pro ActionText Feld aktivieren oder deaktivieren kann.

**Comment by amaierhofer** [comment]
Könnte man das hier über data-attributes lösen? Per default denke ich das attachments schon aktiviert sein sollten. Bei CustomContents würde ich mir wünsche, dass wir das auf der Form Komponente `textarea` oder `fieldset` mit einem `data-attachments=false` attribute deaktivieren könnten

**Comment by carlobeltrame** [comment]
Ja wäre eine Möglichkeit. Dann muss man aber sowohl auf dem Model wie auch im Formular-Template dran denken dass man attachments deaktiviert. Mein PR orientiert sich daran wie es bereits mit required gemacht wird, automatisch anhand der Validatoren auf dem Model. Ist ein Tradeoff zwischen automatisierung und explizitheit.

Übrigens: Da es ein Trix Editor ist, der mit contenteditable arbeitet ists keine textarea, sondern ein paar verschachtelte "normale" divs. Sollte aber trotzdem gehen, einen CSS selector dafür zu schreiben.
